version: '0.1'

services:
  postgres:
    env_file:
      - .env.dev
    environment:
      - POSTGRES_DB=kkujjang_test
      - TZ=$TIME_ZONE
    container_name: $POSTGRES_HOST
    image: postgres:latest
    volumes:
      - ./data/postgres/:/docker-entrypoint-initdb.d/
    restart: always
    tty: true
    stdin_open: true
    ports:
      - $PGPORT:$PGPORT

  mongodb:
    env_file:
      - .env.dev
    environment:
      - MONGO_INITDB_DATABASE=kkujjang_test
      - TZ=$TIME_ZONE
    container_name: $MONGODB_HOST
    volumes:
      - ./data/mongodb/:/docker-entrypoint-initdb.d/mongo-init.js:ro
    image: mongo:latest
    restart: always
    tty: true
    stdin_open: true
    command: mongod --port $MONGODB_PORT
    ports:
      - $MONGODB_PORT:$MONGODB_PORT

  redis:
    env_file:
      - .env.dev
    environment:
      - TZ=$TIME_ZONE
    container_name: $REDIS_HOST
    image: redis/redis-stack-server:latest
    restart: always
    command: redis-server --requirepass $REDIS_PASSWORD --port $REDIS_PORT
    tty: true
    stdin_open: true
    ports:
      - $REDIS_PORT:$REDIS_PORT

  rabbitmq:
    env_file:
      - .env.dev
    environment:
      - RABBITMQ_DEFAULT_USER=$RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS=$RABBITMQ_DEFAULT_PASS
      - TZ=$TIME_ZONE
    container_name: $RABBITMQ_HOST
    image: rabbitmq:3.12.4-management-alpine
    restart: always
    tty: true
    stdin_open: true
    ports:
      - $RABBITMQ_PORT:$RABBITMQ_PORT
      - $RABBITMQ_MANAGER_PORT:$RABBITMQ_MANAGER_PORT

  api:
    container_name: kkujjang-api-server-dev
    env_file:
      - .env.dev
    environment:
      - NODE_ENV=dev
      - TZ=$TIME_ZONE
    image: kkujjang-api-server:dev
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: always
    tty: true
    stdin_open: true
    expose:
      - $HTTP_PORT
    ports:
      - $HTTP_PORT:$HTTP_PORT

  game:
    container_name: kkujjang-game-server-dev
    env_file:
      - .env.dev
    environment:
      - NODE_ENV=dev
      - TZ=$TIME_ZONE
    image: kkujjang-game-server:dev
    build:
      context: .
      dockerfile: Dockerfile.game
    restart: always
    tty: true
    stdin_open: true
    expose:
      - $WS_PORT
    ports:
      - $WS_PORT:$WS_PORT
